
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-engine-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.DemandeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  userId: 'userId',
  montant: 'montant',
  description: 'description',
  type: 'type',
  statut: 'statut',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  factureUrl: 'factureUrl',
  paiementId: 'paiementId'
};

exports.Prisma.PaiementScalarFieldEnum = {
  id: 'id',
  demandeId: 'demandeId',
  montant: 'montant',
  factureUrl: 'factureUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Statut = exports.$Enums.Statut = {
  PENDING: 'PENDING',
  DENIED: 'DENIED',
  VALIDATED: 'VALIDATED'
};

exports.Type = exports.$Enums.Type = {
  DEMANDE: 'DEMANDE',
  PAIEMENT: 'PAIEMENT',
  REMBOURSEMENT: 'REMBOURSEMENT'
};

exports.Prisma.ModelName = {
  Demande: 'Demande',
  Paiement: 'Paiement'
};
/**
 * Create the Client
 */
const config = {
  "generator": {
    "name": "client",
    "provider": {
      "fromEnvVar": null,
      "value": "prisma-client-js"
    },
    "output": {
      "value": "/Users/valentin/src/primitiv-discord-bot/bot/prisma/client",
      "fromEnvVar": null
    },
    "config": {
      "engineType": "library"
    },
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "darwin-arm64",
        "native": true
      }
    ],
    "previewFeatures": [],
    "sourceFilePath": "/Users/valentin/src/primitiv-discord-bot/bot/prisma/schema.prisma",
    "isCustomOutput": true
  },
  "relativeEnvPaths": {
    "rootEnvPath": null,
    "schemaEnvPath": "../../.env"
  },
  "relativePath": "..",
  "clientVersion": "6.19.0",
  "engineVersion": "2ba551f319ab1df4bc874a89965d8b3641056773",
  "datasourceNames": [
    "db"
  ],
  "activeProvider": "postgresql",
  "postinstall": false,
  "inlineDatasources": {
    "db": {
      "url": {
        "fromEnvVar": "DATABASE_URL",
        "value": null
      }
    }
  },
  "inlineSchema": "generator client {\n  provider = \"prisma-client-js\"\n  output   = \"./client\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n  // When using Prisma Accelerate, uncomment the following line:\n  // directUrl = env(\"DIRECT_DATABASE_URL\")\n}\n\nenum Statut {\n  PENDING\n  DENIED\n  VALIDATED\n}\n\nenum Type {\n  DEMANDE\n  PAIEMENT\n  REMBOURSEMENT\n}\n\nmodel Demande {\n  id          Int       @id @default(autoincrement())\n  name        String    @unique\n  userId      String\n  montant     Float\n  description String\n  type        Type\n  statut      Statut    @default(PENDING)\n  createdAt   DateTime  @default(now())\n  updatedAt   DateTime  @updatedAt\n  factureUrl  String? // URL Google Drive de la facture\n  paiementId  Int? // ID de la demande de paiement associée (si type=REMBOURSEMENT)\n  Paiement    Paiement? @relation(fields: [paiementId], references: [id])\n\n  // Index pour les recherches rapides\n  @@index([name])\n  @@index([userId])\n}\n\nmodel Paiement {\n  id         Int       @id @default(autoincrement())\n  demandeId  Int       @unique\n  Demande    Demande[]\n  montant    Float\n  factureUrl String? // URL Google Drive de la facture\n  createdAt  DateTime  @default(now())\n  updatedAt  DateTime  @updatedAt\n}\n",
  "inlineSchemaHash": "0c8adde16c6ae516546b13a5d433f3fcb00e1187574725035b610ff220318cb8",
  "copyEngine": true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse("{\"models\":{\"Demande\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"userId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"montant\",\"kind\":\"scalar\",\"type\":\"Float\"},{\"name\":\"description\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"type\",\"kind\":\"enum\",\"type\":\"Type\"},{\"name\":\"statut\",\"kind\":\"enum\",\"type\":\"Statut\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updatedAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"factureUrl\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"paiementId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"Paiement\",\"kind\":\"object\",\"type\":\"Paiement\",\"relationName\":\"DemandeToPaiement\"}],\"dbName\":null},\"Paiement\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"demandeId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"Demande\",\"kind\":\"object\",\"type\":\"Demande\",\"relationName\":\"DemandeToPaiement\"},{\"name\":\"montant\",\"kind\":\"scalar\",\"type\":\"Float\"},{\"name\":\"factureUrl\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updatedAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {
    DATABASE_URL: typeof globalThis !== 'undefined' && globalThis['DATABASE_URL'] || typeof process !== 'undefined' && process.env && process.env.DATABASE_URL || undefined
  }
})

if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)

